version: 1.0.{build}
os: macos
platform: x64

environment:
  app_name: Test
  output_path: $app_name/builds/ipa
  product_name: Test
  build_version: 1.0.{build}

install:
  - brew update
  - brew install python3
  - python3 -m venv venv
  - source venv/bin/activate
  - pip install -r "$app_name/requirements.txt"
  - brew install --cask flutter
  - brew install cocoapods
  - pod setup
  - flutter doctor

build_script:
  - source venv/bin/activate
  - flet build ipa "$app_name" --output "$output_path" --product "$product_name" --build-version "$build_version"

artifacts:
  - path: $app_name/builds/ipa/**/*.ipa
    name: $app_name Build
