version: 1.0.{build}
os: macos
platform: x64

environment:
  app_name: Markdown
  output_path: builds/ipa
  product_name: Markdown
  build_version: 1.0.{build}

install:
  - brew update
  - brew install python3
  - brew install --cask flutter
  - flutter doctor
  - pip3 install flet

build_script:
  - flet build ipa "$app_name" --output "$output_path" --product "$product_name" --build-version "$build_version"

artifacts:
  - path: builds/ipa/**
    name: Markdown Build
